const fs = require("fs");
const path = require("path");

const url = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL || "";
const anonKey =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY || "";
const enabled = Boolean(url && anonKey);

const contents =
  "// Auto-generated by scripts/inject-config.js — do not edit on Vercel builds.\n" +
  "window.FVGD_CONFIG = {\n" +
  '  supabaseUrl: "' + url + '",\n' +
  '  supabaseAnonKey: "' + anonKey + '",\n' +
  "  supabaseEnabled: " + enabled + "\n" +
  "};\n";

const outPath = path.join(__dirname, "..", "js", "config.js");
fs.writeFileSync(outPath, contents, "utf8");
console.log("Wrote js/config.js (supabaseEnabled=" + enabled + ")");
