const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const outDir = path.join(root, "public");

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function copyRecursive(src, dest) {
  if (!fs.existsSync(src)) {
    console.warn("Skip missing path:", src);
    return;
  }
  const stat = fs.statSync(src);
  if (stat.isDirectory()) {
    ensureDir(dest);
    for (const name of fs.readdirSync(src)) {
      copyRecursive(path.join(src, name), path.join(dest, name));
    }
  } else {
    ensureDir(path.dirname(dest));
    fs.copyFileSync(src, dest);
  }
}

function writeConfig(targetJsConfigPath) {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL || "";
  const anonKey =
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY || "";
  const enabled = Boolean(url && anonKey);

  const contents =
    "// Auto-generated by scripts/vercel-build.js\n" +
    "window.FVGD_CONFIG = {\n" +
    '  supabaseUrl: "' + url + '",\n' +
    '  supabaseAnonKey: "' + anonKey + '",\n' +
    "  supabaseEnabled: " + enabled + "\n" +
    "};\n";

  ensureDir(path.dirname(targetJsConfigPath));
  fs.writeFileSync(targetJsConfigPath, contents, "utf8");
  console.log("Wrote config (supabaseEnabled=" + enabled + ")");
}

function main() {
  console.log("Vercel build starting...");

  if (fs.existsSync(outDir)) {
    fs.rmSync(outDir, { recursive: true, force: true });
  }
  ensureDir(outDir);

  fs.copyFileSync(path.join(root, "index.html"), path.join(outDir, "index.html"));
  fs.copyFileSync(path.join(root, "style.css"), path.join(outDir, "style.css"));

  copyRecursive(path.join(root, "js"), path.join(outDir, "js"));
  copyRecursive(path.join(root, "admin"), path.join(outDir, "admin"));
  copyRecursive(path.join(root, "assets"), path.join(outDir, "assets"));

  writeConfig(path.join(outDir, "js", "config.js"));
  writeConfig(path.join(root, "js", "config.js"));

  const indexPath = path.join(outDir, "index.html");
  if (!fs.existsSync(indexPath)) {
    console.error("BUILD FAILED: public/index.html was not created");
    process.exit(1);
  }

  console.log("Vercel build OK: public/ output ready");
}

main();
